### ISSUE TITLE
Cookie - SameSite

### ISSUE THREAD

**Issue by BKapelari** [fabianpimminger/cookiefox#1]
Hey Fabian,

cool plugin. I really like it!

In FireFox we get the following notice: 
![Bildschirmfoto 2022-04-19 um 16 21 15](https://user-images.githubusercontent.com/4718590/164025759-4410d995-e807-4c3b-a829-8acb0f7ab87d.png)

Here are the settings in the backend:
![Bildschirmfoto 2022-04-19 um 16 21 45](https://user-images.githubusercontent.com/4718590/164025888-81a09a1b-26e9-43b2-a86c-42937c14a9f0.png)

**Comment by fabianpimminger** [comment]
@BKapelari Thanks. It's fixed in the next release.

**Comment by fabianpimminger** [comment]
New version with the fix is released.

**Comment by BKapelari** [comment]
perfect, thank you! :-)
