### ISSUE TITLE
'Cookie information' is hard coded in CategoryConsent.svelte

### ISSUE THREAD

**Issue by xamax71** [fabianpimminger/cookiefox#5]
Hi Fabian,
Thank you for this great plugin.

As I needed to translate it to several languages for my site, I noticed that the string 'Cookie information' is available in the .po files, but it is not translated on the frontend.

Looking at the source code, I noticed this:
line 244 in `CategoryConsent.svelte` 
`<summary class="cookiefox__details-summary">Cookie information</summary>` .

I guess it should read: 
`<summary class="cookiefox__details-summary">{data.notice_button_cookie_information}</summary>`

I saw the variable in `class-frontend.php` line 156.

As I don't use svelte (and to avoid having to correct the script again in case you update it), would it be possible for you to fix it?

Also, would it be possible for the 'Privacy Policy URL' to be a link? (the field does not accept HTML tags).

Thank you!
Max

**Comment by fabianpimminger** [comment]
Hey @xamax71 thank you - you are totally right. Will be released in a few hours :)

**Comment by fabianpimminger** [comment]
@xamax71 released now in 2.0.8 https://github.com/fabianpimminger/cookiefox/releases/tag/2.0.8

**Comment by xamax71** [comment]
Thank you, Fabian! 
Do you have an email where I can send you a PayPal donation?

**Comment by fabianpimminger** [comment]
@xamax71 oh thanks. That's https://paypal.me/fabianpimminger

**Comment by xamax71** [comment]
Hey Fabian, sorry for the late action! 

Just sent you a donation for coffee or glühwein (given the season! :)

When you have time, would it be possible for you to change the field type of the privacy policy field in the cookie tab so to make it a link?

I attach a picture...so maybe it's easier to understand!

![cookie-privacy link](https://github.com/fabianpimminger/cookiefox/assets/6727262/a64dab1f-9e38-42b2-bd63-bcbc8ebf8ffd)

Thank you,
Max
