### ISSUE TITLE
REST API returning Error 404

### ISSUE THREAD

**Issue by Speaka** [fabianpimminger/cookiefox#7]
WP Version 6.4.3 
language DE

When installing from WP Store and adding some Cookies in Settings the js-script  is trying to fetch data from the api endpoint at the following url:
`https://example.com/index.php?rest_route=/cookiefox/v1/cookies?lang=de`
but this endpoint is not returning any data:
> {"code":"rest_no_route","message":"Es wurde keine Route gefunden, die mit der URL und der Request-Methode identisch ist.","data":{"status":404}}

Removing the lang parameter gives the desired output
`https://example.com/index.php?rest_route=/cookiefox/v1/cookies`

Removing the parameter in the fetch call in the built "/assets/frontend/js/main.js" fixes the problem temporarily:  `...fetch(c.api_base+"cookiefox/v1/cookies")...`

I did not get very deep in the code but i guess this is the spot in the source:
https://github.com/fabianpimminger/cookiefox/blob/f8132e6c35f170c9f94760d0f9aa77431d8ba056/src/js/CategoryConsent.svelte#L47

I don't know if the parameter has to be removed or the rest endpoint needs to be tweaked. So unfortunately i dont have persistent solution at hand.

**Comment by fabianpimminger** [comment]
Hi @Speaka - thanks for this bug report. I totally missed this, but I'm investigating now and try to fix this asap.

Best, Fabian

**Comment by fabianpimminger** [comment]
@Speaka new version will be released in a few minutes. This should update your issue.

**Comment by Speaka** [comment]
Works for me. Thank you!
